spring:
  application:
    name : DiscoveryService
  profiles:
    active:
      dev
  cloud:
    config:
      password: 12345678
      username: config-server-user
  config:
    import: configserver:http://localhost:8888

